# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lénárd Szolnoki's programming site
email: mail@lenardszolnoki.com
description: > # this means to ignore newlines until "baseurl:"
        This is my personal website intended mainly for sharing my programming ideas/works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://programming.lenardszolnoki.com" # the base hostname & protocol for your site
github_username: leni536

# Build settings
markdown: kramdown
